const downloadIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M11 3h2v10.17l3.59-3.58L18 11l-6 6-6-6 1.41-1.41L11 13.17V3zM5 19h14v2H5z"/></svg>';
const copyIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M16 1H4a2 2 0 0 0-2 2v12h2V3h12V1zm3 4H8a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h11a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2zm0 16H8V7h11v14z"/></svg>';
const liveRegion=document.querySelector('#ui-status');
function announce(message){if(!liveRegion)return;liveRegion.textContent='';requestAnimationFrame(()=>liveRegion.textContent=message)}
const tones=[{key:'purple',label:'Фиолетовый логотип',color:'#1F0048'},{key:'white',label:'Белый логотип',color:'#FFFFFF'},{key:'black',label:'Черный логотип',color:'#000000'}];
const cards=[...document.querySelectorAll('[data-logo-key]')];
function setTone(card,tone,instant=false){const key=card.dataset.logoKey,preview=card.querySelector('.logo-preview'),img=preview?.querySelector(':scope > img'),btn=card.querySelector('[data-download]'),path=`logos/${key}-${tone}.svg`;card.dataset.currentTone=tone;if(img){if(!instant)img.style.opacity='.15';setTimeout(()=>{img.src=`./assets/${path}`;img.style.opacity='1'},instant?0:100)}preview?.classList.remove('tone-purple','tone-white','tone-black');preview?.classList.add(`tone-${tone}`);if(btn)btn.dataset.download=path;card.querySelectorAll('[data-card-tone]').forEach(b=>{const a=b.dataset.cardTone===tone;b.classList.toggle('is-active',a);b.setAttribute('aria-pressed',String(a))})}
cards.forEach(card=>{const preview=card.querySelector('.logo-preview');if(!preview)return;const controls=document.createElement('div');controls.className='card-tone-switch';controls.setAttribute('role','group');controls.setAttribute('aria-label','Цвет логотипа');tones.forEach(({key,label,color})=>{const b=document.createElement('button');b.type='button';b.dataset.cardTone=key;b.style.setProperty('--tone',color);b.setAttribute('aria-label',label);b.title=label;b.addEventListener('click',()=>setTone(card,key));controls.appendChild(b)});preview.appendChild(controls);setTone(card,'purple',true)});
if('IntersectionObserver'in window){const o=new IntersectionObserver(es=>es.forEach(e=>e.target.classList.toggle('is-in-view',e.isIntersecting&&e.intersectionRatio>=.25)),{threshold:[0,.25,.7]});cards.forEach(c=>o.observe(c))}else cards.forEach(c=>c.classList.add('is-in-view'));
function colorCard({name,hex,rgb,cmyk,pantone,className=''}){return `<article class="${className}" style="--swatch:${hex}"><header><b>${name}</b><div class="color-code"><button class="copy-icon" type="button" data-copy="${hex}" aria-label="Скопировать ${hex}" title="Скопировать код">${copyIcon}</button><strong>${hex}</strong></div></header><dl><div><dt>RGB</dt><dd>${rgb}</dd></div><div><dt>CMYK</dt><dd>${cmyk}</dd></div>${pantone?`<div><dt>Pantone</dt><dd>${pantone}</dd></div>`:''}</dl></article>`}
const grid=document.querySelector('.color-grid');if(grid)grid.innerHTML=[colorCard({name:'Основной сине-фиолетовый',hex:'#1F0048',rgb:'31, 0, 72',cmyk:'95, 100, 25, 50',pantone:'2695 C'}),colorCard({name:'Сиреневый',hex:'#A7A4DF',rgb:'167, 164, 223',cmyk:'30, 30, 0, 0',pantone:'2705 C',className:'light-swatch'}),colorCard({name:'Светлый сиреневый',hex:'#E9E9F5',rgb:'233, 233, 245',cmyk:'9, 8, 0, 1',pantone:'7443 EC',className:'light-swatch'}),colorCard({name:'Черный',hex:'#000000',rgb:'0, 0, 0',cmyk:'0, 0, 0, 100'}),colorCard({name:'Белый',hex:'#FFFFFF',rgb:'255, 255, 255',cmyk:'0, 0, 0, 0',className:'light-swatch'})].join('');
document.querySelectorAll('[data-copy]').forEach(b=>b.addEventListener('click',async()=>{const v=b.dataset.copy,old=b.getAttribute('aria-label');try{await navigator.clipboard.writeText(v);b.classList.add('is-copied');b.setAttribute('aria-label','Скопировано');announce(`Цвет ${v} скопирован`);setTimeout(()=>{b.classList.remove('is-copied');b.setAttribute('aria-label',old||`Скопировать ${v}`)},1200)}catch{window.prompt('Скопируйте значение:',v)}}));
document.querySelectorAll('[data-download]').forEach(b=>{b.innerHTML=downloadIcon;b.addEventListener('click',()=>{const p=b.dataset.download;if(!p)return;const a=document.createElement('a');a.href=`./assets/${p}`;a.download=p.split('/').pop();document.body.appendChild(a);a.click();a.remove();announce(`Скачивание файла ${a.download} началось`)})});
const sidebarLinks=[...document.querySelectorAll('.sidebar nav a[href^="#"]')];const sections=sidebarLinks.map(link=>({link,section:document.querySelector(link.getAttribute('href'))})).filter(x=>x.section);const intro=document.querySelector('.brand-intro'),graphics=document.querySelector('.map-section'),back=document.querySelector('.back-to-top'),topbar=document.querySelector('.topbar'),contextBtns=[...document.querySelectorAll('.button-small,.sidebar-download')];let ticking=false;const reduce=matchMedia('(prefers-reduced-motion: reduce)');
function update(){const vh=innerHeight||1,marker=Math.min(vh*.34,300);let active=sections[0];sections.forEach(x=>{if(x.section.getBoundingClientRect().top<=marker)active=x});if(innerHeight+scrollY>=document.documentElement.scrollHeight-8)active=sections.at(-1);sections.forEach(({link})=>{const a=link===active?.link;link.classList.toggle('is-active',a);a?link.setAttribute('aria-current','location'):link.removeAttribute('aria-current')});if(graphics&&!reduce.matches){const r=graphics.getBoundingClientRect(),p=(vh/2-(r.top+r.height/2))/vh;graphics.style.setProperty('--map-parallax',`${Math.max(-36,Math.min(36,p*36))}px`)}if(intro){const h=topbar?.getBoundingClientRect().height||0,show=intro.getBoundingClientRect().bottom<=h+8&&scrollY>80;back?.classList.toggle('is-visible',show);contextBtns.forEach(b=>b.classList.toggle('is-visible',show))}ticking=false}
function req(){if(ticking)return;ticking=true;requestAnimationFrame(update)}addEventListener('scroll',req,{passive:true});addEventListener('resize',req);addEventListener('pageshow',update);addEventListener('hashchange',update);update();
